### ISSUE TITLE
Typo in the 'About' field

### ISSUE THREAD

**Issue by rjc** [e-zk/after#6]
Hello,

There's a typo in the _About_ field in the project description - _exists_ `->` _exits_.

I also have several suggestions for the text to read a bit better:

- swap the order _in order_ (sic!) to remove the coma (`,`)
- change definite to indefinite article - _the_ `->` _a_
- remove both full stops - IMHO looks better aesthetically :^)

So the the whole thing reads:

     echo a string to stdout after a specified process exits (OpenBSD)

**Comment by e-zk** [comment]
Thanks for that. Typos do my head in, glad you caught that!  
These seem like reasonable changes.
